//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class persona
    {
        public int Id { get; set; }
        public string nombre { get; set; }
        public string correo { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
    }
}
